/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminCitasRouteImport } from './routes/admin-citas'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as InvisalignRouteImport } from './routes/invisalign'
import { Route as OdontologiaEsteticaRouteImport } from './routes/odontologia-estetica'
import { Route as OdontopediatriaRouteImport } from './routes/odontopediatria'
import { Route as OpinionesRouteImport } from './routes/opiniones'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as UrgenciasDentalesMurciaRouteImport } from './routes/urgencias-dentales-murcia'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitasRoute = AdminCitasRouteImport.update({
  id: '/admin-citas',
  path: '/admin-citas',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisalignRoute = InvisalignRouteImport.update({
  id: '/invisalign',
  path: '/invisalign',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontologiaEsteticaRoute = OdontologiaEsteticaRouteImport.update({
  id: '/odontologia-estetica',
  path: '/odontologia-estetica',
  getParentRoute: () => rootRouteImport,
} as any)
const OdontopediatriaRoute = OdontopediatriaRouteImport.update({
  id: '/odontopediatria',
  path: '/odontopediatria',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionesRoute = OpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgenciasDentalesMurciaRoute = UrgenciasDentalesMurciaRouteImport.update({
  id: '/urgencias-dentales-murcia',
  path: '/urgencias-dentales-murcia',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-citas': typeof AdminCitasRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/invisalign': typeof InvisalignRoute
  '/odontologia-estetica': typeof OdontologiaEsteticaRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/opiniones': typeof OpinionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/urgencias-dentales-murcia': typeof UrgenciasDentalesMurciaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-citas': typeof AdminCitasRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/invisalign': typeof InvisalignRoute
  '/odontologia-estetica': typeof OdontologiaEsteticaRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/opiniones': typeof OpinionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/urgencias-dentales-murcia': typeof UrgenciasDentalesMurciaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-citas': typeof AdminCitasRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/invisalign': typeof InvisalignRoute
  '/odontologia-estetica': typeof OdontologiaEsteticaRoute
  '/odontopediatria': typeof OdontopediatriaRoute
  '/opiniones': typeof OpinionesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/urgencias-dentales-murcia': typeof UrgenciasDentalesMurciaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-citas'
    | '/aviso-legal'
    | '/contacto'
    | '/invisalign'
    | '/odontologia-estetica'
    | '/odontopediatria'
    | '/opiniones'
    | '/politica-de-privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/urgencias-dentales-murcia'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-citas'
    | '/aviso-legal'
    | '/contacto'
    | '/invisalign'
    | '/odontologia-estetica'
    | '/odontopediatria'
    | '/opiniones'
    | '/politica-de-privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/urgencias-dentales-murcia'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/admin-citas'
    | '/aviso-legal'
    | '/contacto'
    | '/invisalign'
    | '/odontologia-estetica'
    | '/odontopediatria'
    | '/opiniones'
    | '/politica-de-privacidad'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/urgencias-dentales-murcia'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCitasRoute: typeof AdminCitasRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  InvisalignRoute: typeof InvisalignRoute
  OdontologiaEsteticaRoute: typeof OdontologiaEsteticaRoute
  OdontopediatriaRoute: typeof OdontopediatriaRoute
  OpinionesRoute: typeof OpinionesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  UrgenciasDentalesMurciaRoute: typeof UrgenciasDentalesMurciaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-citas': {
      id: '/admin-citas'
      path: '/admin-citas'
      fullPath: '/admin-citas'
      preLoaderRoute: typeof AdminCitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisalign': {
      id: '/invisalign'
      path: '/invisalign'
      fullPath: '/invisalign'
      preLoaderRoute: typeof InvisalignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontologia-estetica': {
      id: '/odontologia-estetica'
      path: '/odontologia-estetica'
      fullPath: '/odontologia-estetica'
      preLoaderRoute: typeof OdontologiaEsteticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odontopediatria': {
      id: '/odontopediatria'
      path: '/odontopediatria'
      fullPath: '/odontopediatria'
      preLoaderRoute: typeof OdontopediatriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opiniones': {
      id: '/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof OpinionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgencias-dentales-murcia': {
      id: '/urgencias-dentales-murcia'
      path: '/urgencias-dentales-murcia'
      fullPath: '/urgencias-dentales-murcia'
      preLoaderRoute: typeof UrgenciasDentalesMurciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCitasRoute: AdminCitasRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  InvisalignRoute: InvisalignRoute,
  OdontologiaEsteticaRoute: OdontologiaEsteticaRoute,
  OdontopediatriaRoute: OdontopediatriaRoute,
  OpinionesRoute: OpinionesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  UrgenciasDentalesMurciaRoute: UrgenciasDentalesMurciaRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
